<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1
The following array is given:  
A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]])  


Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.  



Tip: Use the np.where() function.  



Expected result:  



[[ 4.99  3.49  9.99]  
 [ 1.99  9.99 10.  ]  
 [10.    2.39  7.29]]  

In [11]:
import numpy as np
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
print(np.where( A > 10, 10, A ))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


###Exercise 2
Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.  
A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]])  


Tip: Use the np.ravel() function.  



Expected result:  



[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]

In [13]:
import numpy as np
A = np.array([[4.99, 3.49,9.99],
              [1.99,9.99,14.99],
              [14.99,2.39,7.29]])

print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


### Exercise 3
The following array is given:  



A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]])  


Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.



Tip: Use the np.zeros_like() function.



Expected result:



[[0. 0. 0.]  
 [0. 0. 0.]  
 [0. 0. 0.]]  

In [14]:
import numpy as np

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
print(np.zeros_like(A))



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
