<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Exercise 1
The following array is given:



A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 14.99],  
              [14.99, 2.39, 7.29]])  


Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.



Tip: Use the np.full_like() function.



Expected result:



[[9.99 9.99 9.99]  
 [9.99 9.99 9.99]  
 [9.99 9.99 9.99]]  


In [1]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
print(np.full_like(A,9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


###Exercise 2
Using Numpy create a two-dimensional array (lower triangular matrix):



array([[1., 0., 0., 0., 0.],  
       [1., 1., 0., 0., 0.],  
       [1., 1., 1., 0., 0.],  
       [1., 1., 1., 1., 0.],  
       [1., 1., 1., 1., 1.]])  


In response, print result to the console.



Tip: Use the np.tri() function.



Expected result:



[[1. 0. 0. 0. 0.]  
 [1. 1. 0. 0. 0.]  
 [1. 1. 1. 0. 0.]  
 [1. 1. 1. 1. 0.]  
 [1. 1. 1. 1. 1.]]  

In [6]:
import numpy as np
print(np.tri(5))


[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


### Exercise 3
Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.  



Example:  



[[[4 5 4 2]  
  [6 3 5 1]  
  [5 2 1 2]]  

 [[7 2 3 1]  
  [6 2 0 9]  
  [0 1 9 1]]]  

In [15]:
import numpy as np
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],

              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])
print(A)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]


###Exercise 4
Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.

In [20]:
import numpy as np
image = np.random.randint(0, 255, size=(200, 300), dtype=np.uint8)
print(image)

[[159 129  77 ...  98   2  40]
 [128 219 105 ... 191 138 140]
 [135 155  68 ... 161 231   3]
 ...
 [109  81  87 ... 251 222 153]
 [206 174  74 ... 105 165  99]
 [193 178  31 ...  82  89  43]]
