<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Exercise 1
The following array is given:



A = np.array([[5, 1, 2, 1, 2],  
              [9, 1, 9, 7, 5],  
              [4, 1, 5, 7, 9]])  
Extract all unique values of this array as a list and print it to the console.  



Tip: Use the np.unique() function.  



Expected result:  



[1 2 4 5 7 9]  

In [5]:
import numpy as np
A = np.array ([[5, 1, 2, 1, 2],
[9, 1, 9, 7, 5],
[4, 1, 5, 7, 9]])

print(np.unique(A))

[1 2 4 5 7 9]


In [9]:
import numpy as np
x = np.arange(48).reshape(-1,8)
x=np.pad(x, (1,1), 'constant')
print(np.unique(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


### Exercise 2
The following array is given:  
A = np.array  
([[0.4, 0.3, 0.3],  
              [0.1, 0.1, 0.8],  
              [0.2, 0.5, 0.3]])  


Return a list of indexes with maximum values for each row from this array and print it to the console.



Tip: Use the np.argmax() function.  



Expected result:  



[0 2 1]  


In [26]:
import numpy as np
A=np.array ([[0.4, 0.3, 0.3],
            [0.1, 0.1, 0.8],
            [0.2, 0.5, 0.3]])

print(np.argmax(A, axis=0))

[0 2 1]


### Exercise 3
The following array is given:  
A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 4.99],  
              [14.99, 2.39, 7.29]])  


Sort this array:

by row (ascending)

by column (ascending)

And print result to the console as shown below.



Tip: Use the np.sort() function.



Expected result:



[[ 3.49  4.99  9.99]  
 [ 1.99  4.99  9.99]  
 [ 2.39  7.29 14.99]]  
[[ 1.99  2.39  4.99]  
 [ 4.99  3.49  7.29]  
 [14.99  9.99  9.99]]  


In [29]:
import numpy as np
A=np.array([[4.99, 3.49, 9.99],
[1.99, 9.99, 4.99],
[14.99, 2.39, 7.29]])
print(np.sort(A))
print(np.sort(A,0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


### Exercise 4
Extract all elements from the following array with a value greater than 8 and print result to the console.



A = np.array([[4.99, 3.49, 9.99],  
              [1.99, 9.99, 4.99],  
              [14.99, 2.39, 7.29]])  


Expected result:  



[ 9.99  9.99 14.99]  

In [34]:
import numpy as np
A = np.array([[4.99,3.49,9.99],
              [1.99,9.99,4.99],
              [14.99,2.39,7.29]])
print(A[A > 8])
print(A[A<2])

[ 9.99  9.99 14.99]
[1.99]
