<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercie 1
Expected result:  
[ True False False False]

In [4]:
import numpy as np


A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(np.greater(A,B))
#or
#print(A>B)


[ True False False False]


### Exercice 2
Expected result:  
[[0 0 0 0]  
 [0 0 0 0]  
 [0 0 0 0]  
 [0 0 0 0]]

In [8]:
import numpy as np
A=np.zeros((3,4), dtype=int)
print(A)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Exercice 3
Expected result:  
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]  
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]  


In [12]:
import numpy as np
A=np.full((10,10),"255.", dtype=float)
print(A)

#verbose
#print(np.full(shape=(10, 10), fill_value=255, dtype='float'))

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
