<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercice 1
Using Numpy create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.  
Expected result:  
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33  
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57  
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81  
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]  


In [12]:
import numpy as np
A=np.arange(10,100,dtype=int)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### Exercice 2
Using Numpy create the following array:  
[[10 11 12 13 14 15 16 17 18 19]  
 [20 21 22 23 24 25 26 27 28 29]  
 [30 31 32 33 34 35 36 37 38 39]  
 [40 41 42 43 44 45 46 47 48 49]  
 [50 51 52 53 54 55 56 57 58 59]  
 [60 61 62 63 64 65 66 67 68 69]  
 [70 71 72 73 74 75 76 77 78 79]  
 [80 81 82 83 84 85 86 87 88 89]  
 [90 91 92 93 94 95 96 97 98 99]]  

In [21]:
import numpy as np
A=np.arange(10,100,dtype=int)
A=A.reshape(9,10)
print(A)

#More proficient: print(np.arange(10, 100).reshape(9, 10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Exercice 3
Using Numpy create a 6x6 two-dimensional array - identity matrix with int data type. Print this array to the console as shown below.
Expected result:  
[[1 0 0 0 0 0]  
 [0 1 0 0 0 0]  
 [0 0 1 0 0 0]  
 [0 0 0 1 0 0]  
 [0 0 0 0 1 0]  
 [0 0 0 0 0 1]]  


In [24]:
import numpy as np
A=np.eye(6, dtype=int)
print(A)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
