<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1
Using Numpy create the following two-dimensional array:  
[[0 0 0 0 0 0]  
 [0 1 0 0 0 0]  
 [0 0 2 0 0 0]  
 [0 0 0 3 0 0]  
 [0 0 0 0 4 0]  
 [0 0 0 0 0 5]]  
Print result to the console as shown below.  
Tip: Use the np.diag() function.  



In [4]:
import numpy as np
x=np.array([0,1,2,3,4,5])
A=np.diag(x,0)
print(A)
# Solution : print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


###Exercise 2  
Using Numpy create the following array :  
([[ 0,  1,  2,  3],  
       [ 4,  5,  6,  7],  
       [ 8,  9, 10, 11]])  
Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.  
Tip: Use the np.save() and np.load() functions.  

In [10]:
import numpy as np
x=np.arange(12).reshape(-1, 4)
np.save("array.npy",x)
np.load("array.npy")



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Exercise 3
Using Numpy create the following array:  
([[ 0,  1,  2,  3],  
       [ 4,  5,  6,  7],  
       [ 8,  9, 10, 11]])  
Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.  
Tip: Use the np.savetxt() and np.loadtxt() functions.

In [26]:
import numpy as np
x=np.arange(12)
x=x.reshape(3,4)
np.savetxt("array.txt",x)
A=np.loadtxt("array.txt")
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
