<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Exercise 1
Using Numpy create and convert the following array into the list:  
array([[ 0,  1,  2,  3],  
       [ 4,  5,  6,  7],  
       [ 8,  9, 10, 11]])  

In response, print list to the console.  

Tip: Use the np.array.tolist() method.  

Expected output:



[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [11]:
import numpy as np
x=np.arange(12).reshape(3,4)
print(x.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### Exercise 2
The following array is given:  
array  
([[ 0,  1,  2,  3],  
[ 4,  5,  6,  7],  
[ 8,  9, 10, 11]])  

Using the slice operator, transform this array into the following:  
array  
([[ 8,  9, 10, 11],  
[ 4,  5,  6,  7],  
[ 0,  1,  2,  3]])  
In response, print transformed array to the console.  

Expected output:  

[[ 8  9 10 11]  
 [ 4  5  6  7]  
 [ 0  1  2  3]]  


In [10]:
import numpy as np
x=np.arange(12).reshape(-1,4)
print(x[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


### Exercise 3
The following array:  
array  
([[1., 1., 1., 1.],  
       [1., 1., 1., 1.],  
       [1., 1., 1., 1.],  
       [1., 1., 1., 1.]])  


transform to this array:  

array  
([[0., 0., 0., 0., 0., 0.],  
       [0., 1., 1., 1., 1., 0.],  
       [0., 1., 1., 1., 1., 0.],  
       [0., 1., 1., 1., 1., 0.],  
       [0., 1., 1., 1., 1., 0.],  
       [0., 0., 0., 0., 0., 0.]])  


In response, print transformed array to the console.



Tip: Use the np.pad() function.



Expected output:  



[[0. 0. 0. 0. 0. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 1. 1. 1. 1. 0.]  
 [0. 0. 0. 0. 0. 0.]]  


In [19]:
from ast import Constant
import numpy as np
x = np.ones(16).reshape(4,4)
x = np.pad(x, (1,1), 'constant')
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
