<a href="https://colab.research.google.com/github/ValentinAdamIT/data_science/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Exercise 1
The following array:  
array  
([[0, 0, 0, 0, 0, 0],  
       [0, 0, 0, 0, 0, 0],  
       [0, 0, 0, 0, 0, 0],  
       [0, 0, 0, 0, 0, 0],  
       [0, 0, 0, 0, 0, 0],  
       [0, 0, 0, 0, 0, 0]])  


transform to the following:  



array  
([[10,  0, 10,  0, 10,  0],  
       [ 5,  0,  5,  0,  5,  0],  
       [10,  0, 10,  0, 10,  0],  
       [ 5,  0,  5,  0,  5,  0],  
       [10,  0, 10,  0, 10,  0],  
       [ 5,  0,  5,  0,  5,  0]])  


In response, print transformed array to the console.



Tip: Use the slice operator and assign the appropriate values.



Expected output:



[[10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]  
 [10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]  
 [10  0 10  0 10  0]  
 [ 5  0  5  0  5  0]]  


In [11]:
import numpy as np
x=np.zeros(36, dtype=int).reshape(6,6)
# x[::2, ::2] = 10: Assigns the value 10 to every element in even rows and even columns.
x[::2, ::2] = 10
# x[1::2, ::2] = 5: Assigns the value 5 to every element in odd rows and even columns.
x[1::2, ::2] = 5
print(x)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


###Exercise 2
Combine the following arrays into one as shown below and print it to the console.



A = np.arange(12).reshape(-1, 4)  
B = np.array([[4, 3, 7, 2],  
              [0, 5, 2, 6]])  


Tip: Use the np.append() function.  



Expected result:  



[[ 0  1  2  3]  
 [ 4  5  6  7]  
 [ 8  9 10 11]  
 [ 4  3  7  2]  
 [ 0  5  2  6]]  


In [22]:
import numpy as np
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2], [0, 5, 2, 6]])
print(np.append(A,B,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


### Exercise 3
The following arrays are given:  



A = np.arange(8).reshape(-1, 4)  
B = np.array([[9, 10, 11, 3],  
              [2, 8, 0, 9]])        


Extract the same elements (intersection) of the arrays as a list and print result to the console.  



Tip: Use the np.intersect1d() function.  



Expected result:  



[0 2 3]  


In [25]:
import numpy as np
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
[2, 8, 0, 9]])
print(np.intersect1d(A,B))

[0 2 3]


In [31]:
import numpy as np
A=np.arange(15).reshape(-1,5)
B=np.arange(20).reshape(-1,5)
print(np.intersect1d(A,B))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
